from bs4.element import ResultSet
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
from time import sleep
import cryptocompare
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
import json
import os

driver_path = "C:/Program Files/BraveSoftware/Brave-Browser/Application/chromedriver.exe"
brave_path = "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"

option = webdriver.ChromeOptions()
# option.add_argument('headless')
option.binary_location = brave_path
driver = webdriver.Chrome(executable_path=driver_path, chrome_options=option)

# chrome_options = webdriver.ChromeOptions()
# chrome_options.binary_location = os.environ.get("GOOGLE_CHROME_BIN")
# chrome_options.add_argument('--window-size=1920,1080')
# # chrome_options.add_argument("--headless")
# chrome_options.add_argument("--disable-dev-shm-usage")
# chrome_options.add_argument("--no-sandbox")
# chrome_options.add_argument('--disable-gpu')
# driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), chrome_options=chrome_options)


names=[]
driver.get("https://www.instagram.com/")
sleep(3)
username = driver.find_element_by_xpath('//*[@id="loginForm"]/div/div[1]/div/label/input')
password = driver.find_element_by_xpath('//*[@id="loginForm"]/div/div[2]/div/label/input')

# Your instagram Username and Password 
username1 = ""
password1 = ""
username.send_keys(username1)
password.send_keys(password1)
login_button = driver.find_element_by_xpath('//*[@id="loginForm"]/div/div[3]')
login_button.click()
sleep(4)
notNow = driver.find_element_by_xpath('//*[@id="react-root"]/section/main/div/div/div/div/button')
notNow.click()
sleep(4)
notNow_not = driver.find_element_by_xpath('/html/body/div[4]/div/div/div/div[3]/button[2]')
notNow_not.click()

while True:
    sleep(2)
    driver.get("https://www.instagram.com/direct/inbox/")
    sleep(2)
    content2 = driver.page_source
    sleep(2)
    soup = BeautifulSoup(content2, 'html.parser')
    for a in soup.findAll('span'):
        name = str(a.find('span', {"class": "_7UhW9 xLCgt qyrsm KV-D4 se6yk"}))
        if 'btc' in name:
            username = str(soup.find('div', {"class": "_7UhW9 xLCgt qyrsm KV-D4 fDxYl"}))
            username = username.split('<div class="_7UhW9 xLCgt qyrsm KV-D4 fDxYl">')
            username = ''.join(username)
            username = username.split('</div>')
            username = ''.join(username)
            driver.get('https://www.instagram.com/' + username + '/')
            sleep(2)
            massage1 = driver.find_element_by_css_selector('#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm.bPdm3 > div > div.Igw0E.IwRSH.eGOV_.vwCYk.i0EQd > button')
            massage1.click()
            sleep(2)
            send = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea')
            p = cryptocompare.get_price('BTC', currency='CAD')
            result = json.dumps(p)
            result = ''.join(result)
            result = result.split("{")
            result = ''.join(result)
            result = result.split("}")
            result = ''.join(result)
            result = result.split('"')
            result = ''.join(result)
            send.send_keys(result)
            sleep(1)
            send_button = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/button')
            send_button.click()
            sleep(2)
            driver.get("https://www.instagram.com/direct/inbox/")
        if 'eth' in name:
            username = str(soup.find('div', {"class": "_7UhW9 xLCgt qyrsm KV-D4 fDxYl"}))
            username = username.split('<div class="_7UhW9 xLCgt qyrsm KV-D4 fDxYl">')
            username = ''.join(username)
            username = username.split('</div>')
            username = ''.join(username)
            driver.get('https://www.instagram.com/' + username + '/')
            sleep(2)
            massage1 = driver.find_element_by_css_selector('#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm.bPdm3 > div > div.Igw0E.IwRSH.eGOV_.vwCYk.i0EQd > button')
            massage1.click()
            sleep(2)
            send = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea')
            p = cryptocompare.get_price('ETH', currency='CAD')
            result = json.dumps(p)
            result = ''.join(result)
            result = result.split("{")
            result = ''.join(result)
            result = result.split("}")
            result = ''.join(result)
            result = result.split('"')
            result = ''.join(result)
            send.send_keys(result)
            sleep(1)
            send_button = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/button')
            send_button.click()
            sleep(2)
            driver.get("https://www.instagram.com/direct/inbox/")
        if 'usdt' in name:
            username = str(soup.find('div', {"class": "_7UhW9 xLCgt qyrsm KV-D4 fDxYl"}))
            username = username.split('<div class="_7UhW9 xLCgt qyrsm KV-D4 fDxYl">')
            username = ''.join(username)
            username = username.split('</div>')
            username = ''.join(username)
            driver.get('https://www.instagram.com/' + username + '/')
            sleep(2)
            massage1 = driver.find_element_by_css_selector('#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm.bPdm3 > div > div.Igw0E.IwRSH.eGOV_.vwCYk.i0EQd > button')
            massage1.click()
            sleep(2)
            send = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea')
            p = cryptocompare.get_price('USDT', currency='CAD')
            result = json.dumps(p)
            result = ''.join(result)
            result = result.split("{")
            result = ''.join(result)
            result = result.split("}")
            result = ''.join(result)
            result = result.split('"')
            result = ''.join(result)
            send.send_keys(result)
            sleep(1)
            send_button = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/button')
            send_button.click()
            sleep(2)
            driver.get("https://www.instagram.com/direct/inbox/")
        if 'bnb' in name:
            username = str(soup.find('div', {"class": "_7UhW9 xLCgt qyrsm KV-D4 fDxYl"}))
            username = username.split('<div class="_7UhW9 xLCgt qyrsm KV-D4 fDxYl">')
            username = ''.join(username)
            username = username.split('</div>')
            username = ''.join(username)
            driver.get('https://www.instagram.com/' + username + '/')
            sleep(2)
            massage1 = driver.find_element_by_css_selector('#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm.bPdm3 > div > div.Igw0E.IwRSH.eGOV_.vwCYk.i0EQd > button')
            massage1.click()
            sleep(2)
            send = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea')
            p = cryptocompare.get_price('BNB', currency='CAD')
            result = json.dumps(p)
            result = ''.join(result)
            result = result.split("{")
            result = ''.join(result)
            result = result.split("}")
            result = ''.join(result)
            result = result.split('"')
            result = ''.join(result)
            send.send_keys(result)
            sleep(1)
            send_button = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/button')
            send_button.click()
            sleep(2)
            driver.get("https://www.instagram.com/direct/inbox/")
        if 'ada' in name:
            username = str(soup.find('div', {"class": "_7UhW9 xLCgt qyrsm KV-D4 fDxYl"}))
            username = username.split('<div class="_7UhW9 xLCgt qyrsm KV-D4 fDxYl">')
            username = ''.join(username)
            username = username.split('</div>')
            username = ''.join(username)
            driver.get('https://www.instagram.com/' + username + '/')
            sleep(2)
            massage1 = driver.find_element_by_css_selector('#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm.bPdm3 > div > div.Igw0E.IwRSH.eGOV_.vwCYk.i0EQd > button')
            massage1.click()
            sleep(2)
            send = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea')
            p = cryptocompare.get_price('ADA', currency='CAD')
            result = json.dumps(p)
            result = ''.join(result)
            result = result.split("{")
            result = ''.join(result)
            result = result.split("}")
            result = ''.join(result)
            result = result.split('"')
            result = ''.join(result)
            send.send_keys(result)
            sleep(1)
            send_button = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/button')
            send_button.click()
            sleep(2)
            driver.get("https://www.instagram.com/direct/inbox/")
        if 'doge' in name:
            username = str(soup.find('div', {"class": "_7UhW9 xLCgt qyrsm KV-D4 fDxYl"}))
            username = username.split('<div class="_7UhW9 xLCgt qyrsm KV-D4 fDxYl">')
            username = ''.join(username)
            username = username.split('</div>')
            username = ''.join(username)
            driver.get('https://www.instagram.com/' + username + '/')
            sleep(2)
            massage1 = driver.find_element_by_css_selector('#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm.bPdm3 > div > div.Igw0E.IwRSH.eGOV_.vwCYk.i0EQd > button')
            massage1.click()
            sleep(2)
            send = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea')
            p = cryptocompare.get_price('DOGE', currency='CAD')
            result = json.dumps(p)
            result = ''.join(result)
            result = result.split("{")
            result = ''.join(result)
            result = result.split("}")
            result = ''.join(result)
            result = result.split('"')
            result = ''.join(result)
            send.send_keys(result)
            sleep(1)
            send_button = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/button')
            send_button.click()
            sleep(2)
            driver.get("https://www.instagram.com/direct/inbox/")
        if 'xrp' in name:
            username = str(soup.find('div', {"class": "_7UhW9 xLCgt qyrsm KV-D4 fDxYl"}))
            username = username.split('<div class="_7UhW9 xLCgt qyrsm KV-D4 fDxYl">')
            username = ''.join(username)
            username = username.split('</div>')
            username = ''.join(username)
            driver.get('https://www.instagram.com/' + username + '/')
            sleep(2)
            massage1 = driver.find_element_by_css_selector('#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm.bPdm3 > div > div.Igw0E.IwRSH.eGOV_.vwCYk.i0EQd > button')
            massage1.click()
            sleep(2)
            send = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea')
            p = cryptocompare.get_price('XRP', currency='CAD')
            result = json.dumps(p)
            result = ''.join(result)
            result = result.split("{")
            result = ''.join(result)
            result = result.split("}")
            result = ''.join(result)
            result = result.split('"')
            result = ''.join(result)
            send.send_keys(result)
            sleep(1)
            send_button = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/button')
            send_button.click()
            sleep(2)
            driver.get("https://www.instagram.com/direct/inbox/")
        if 'dot' in name:
            username = str(soup.find('div', {"class": "_7UhW9 xLCgt qyrsm KV-D4 fDxYl"}))
            username = username.split('<div class="_7UhW9 xLCgt qyrsm KV-D4 fDxYl">')
            username = ''.join(username)
            username = username.split('</div>')
            username = ''.join(username)
            driver.get('https://www.instagram.com/' + username + '/')
            sleep(2)
            massage1 = driver.find_element_by_css_selector('#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm.bPdm3 > div > div.Igw0E.IwRSH.eGOV_.vwCYk.i0EQd > button')
            massage1.click()
            sleep(2)
            send = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea')
            p = cryptocompare.get_price('DOT', currency='CAD')
            result = json.dumps(p)
            result = ''.join(result)
            result = result.split("{")
            result = ''.join(result)
            result = result.split("}")
            result = ''.join(result)
            result = result.split('"')
            result = ''.join(result)
            send.send_keys(result)
            sleep(1)
            send_button = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/button')
            send_button.click()
            sleep(2)
            driver.get("https://www.instagram.com/direct/inbox/")
        if 'uni' in name:
            username = str(soup.find('div', {"class": "_7UhW9 xLCgt qyrsm KV-D4 fDxYl"}))
            username = username.split('<div class="_7UhW9 xLCgt qyrsm KV-D4 fDxYl">')
            username = ''.join(username)
            username = username.split('</div>')
            username = ''.join(username)
            driver.get('https://www.instagram.com/' + username + '/')
            sleep(2)
            massage1 = driver.find_element_by_css_selector('#react-root > section > main > div > header > section > div.nZSzR > div.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm.bPdm3 > div > div.Igw0E.IwRSH.eGOV_.vwCYk.i0EQd > button')
            massage1.click()
            sleep(2)
            send = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea')
            p = cryptocompare.get_price('UNI', currency='CAD')
            result = json.dumps(p)
            result = ''.join(result)
            result = result.split("{")
            result = ''.join(result)
            result = result.split("}")
            result = ''.join(result)
            result = result.split('"')
            result = ''.join(result)
            send.send_keys(result)
            sleep(1)
            send_button = driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/button')
            send_button.click()
            sleep(2)
            driver.get("https://www.instagram.com/direct/inbox/")
    sleep(5)
    driver.get('https://www.google.com/')
    sleep(2)